-- Medios de pago para compra mostrador (idempotente en PostgreSQL 15+)
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'COUNTER_CASH';
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'COUNTER_CREDIT_CARD';
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'COUNTER_DEBIT_CARD';
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'COUNTER_TRANSFER';
